import React from "react";
import { Page } from "../src/components/common/Page";
import Typography from "@material-ui/core/Typography";
import { Container } from '@material-ui/core';
import Table from './cookiesTable'

const PrivacyPolicy = (props: any) => {
    return (
        <Page>
            <Container>
            <h2>Privacy Policy</h2>
                <Typography variant="body1">
                This Privacy Policy is effective <strong>March 13, 2020</strong> for all users.
                This Privacy Policy describes our policies on the collection, use, and disclosure of information about you in connection with your use of our services, including those offered through our websites, emails, and mobile applications (collectively, the <strong>“Service”</strong>). The terms <strong>“we”, “us”, and “Goblaq”</strong> refer to Buy Black Houston., a Delaware corporation with its headquarters in Houston, Texas. When you use the Service, you consent to our collection, use, and disclosure of information about you as described in this Privacy Policy.
                    <ol>
                        <li>INFORMATION WE COLLECT AND HOW WE USE IT</li>
                        We may collect and store information about you in connection with your use of the Service, including any information you transmit to or through the Service. We use that information to provide the Service’s functionality, fulfill your requests, improve the Service’s quality, engage in research and analysis relating to the Service, personalize your experience, track usage of the Service, provide feedback to third party businesses that are listed on the Service, display relevant advertising, market the Service, provide customer support, message you, back up our systems, allow for disaster recovery, enhance the security of the Service, and comply with legal obligations. Even when we do not retain such information, it still must be transmitted to our servers initially and stored long enough to process.
                        <br/>
                        <br/>
                        Please also note:
                            <ol type="1">
                                <li><strong>Account Information:</strong> If you create a Goblaq account, we may store and use the information you provide during that process, such as your full name, email address, zip code, physical address, and other information you may provide with your account, such as your gender, phone number, and birth date. We may publicly display your first name and last initial, as well as any photo or other content you submit through the registration process, as part of your account profile. You can modify some of the information associated with your account through your <a href="">account settings</a>. If you believe that someone has created an unauthorized account depicting you or your likeness, you can request its removal by flagging it.</li>
                                <li><strong>Public Content:</strong> Your contributions to the Service are intended for public consumption and are therefore viewable by the public, including your photos, ratings, reviews, tips, lists, collections, compliments, Ask the Community posts, Goblaq Talk posts, and edits to business listing information. Your account profile (e.g., first name, last initial, city, neighborhood, month joined, profile photos and friends) is also intended for public consumption, as is some of your other activity through the Service, like how you vote on other people’s contributions (e.g., useful, funny, cool, helpful, not helpful), where you check-in, which users you follow, and which businesses you bookmark. You can limit the public nature of some of these activities through your <a href="">account settings</a>.</li>
                                <li><strong>Contacts:</strong> You can invite others to join or become your friend on Goblaq by providing us with their contact information, or by allowing us to access your contacts from your computer, mobile device, or third party sites to select which individuals you want to invite. If you allow us to access your contacts, we may transmit that information to our servers long enough to process your invitations.</li>
                                <li><strong>Communications:</strong> When you sign up for an account or use certain features, you are opting to receive messages from other users, businesses, and Goblaq. You can manage some of your messaging preferences through your <a href="">account settings</a>, but note that you cannot opt out of receiving certain administrative, transactional, or legal messages from Goblaq. For example, if you make a reservation, order food, place yourself on a waitlist, or request a quote from a business through the Service, we may send you messages about your transaction using the contact information you provide, including through automated SMS text messages to your phone number. We may also track your actions in response to the messages you receive from us or through the Service, such as whether you deleted, opened, or forwarded such messages. If you exchange messages with others through the Service, we may store them in order to process and deliver them, allow you to manage them, and we may review and disclose them in connection with investigations related to use of the Service, as well as our efforts to improve the Service. We may not deliver messages that we believe are objectionable, such as spam messages, fraudulent solicitations, or requests to exchange reviews for compensation. If you send or receive messages through the Service via SMS text message, we may log phone numbers, phone carriers, and the date and time that the messages were processed. Carriers may charge recipients for texts that they receive. We may also store information that you provide through communications to us, including from phone calls, letters, emails and other electronic messages, or in person. If you are a representative of a business listed on Goblaq, we may contact you, including by phone or email, using the contact information you provide us, make publicly available, or that we have on record for your business. Our calls with you may be monitored and recorded for quality purposes.</li>
                                <li><strong>Transactions:</strong> If you initiate a transaction through the Service, such as a reservation or purchase, we may collect and store information about you, such as your name, phone number, address, email, and payment information (such as a credit card number and expiration date), as well as any other information you provide to us, in order to process your transaction, send communications about them to you, and populate forms for future transactions. This information may be shared with third parties, and third parties may share such information with us, for the same purposes. When you submit credit card numbers, we encrypt that information using industry standard technology. If you write reviews about businesses with which you transact through the Service, we may publicly display the fact that you transacted with those businesses. For example, if you make a dinner reservation through the Service and write a review about your experience, we may publicly display the fact that you made your dinner reservation through the Service.</li>
                                <li><strong>Activity:</strong> We may store information about your use of the Service, such as your search activity, the pages you view, the date and time of your visit, businesses you call using our mobile applications, and reservations and purchases you make through the Service. We also may store information that your computer or mobile device may provide to us in connection with your use of the Service, such as your browser type, type of computer or mobile device, browser language, IP address, WiFi information such as SSID, mobile carrier, phone number, unique device identifier, advertising identifier, location (including geolocation, beacon based location, and GPS location), and requested and referring URLs. We may also receive and store your location whenever our mobile applications are running, including when running in the background, if you enable our mobile apps to access such information in the course of using the Service. You may be able to limit or disallow our use of certain location data through your device or browser settings, for example by adjusting the “Location Services” settings for our applications in iOS privacy settings.</li>
                                <li><strong>Different Devices:</strong> You may access the Service through different devices (e.g., your mobile phone or desktop computer) and different platforms (e.g., the Goblaq website or Goblaq mobile app). The information that we collect and store through those different uses may be cross-referenced and combined, and your contributions through one Goblaq platform will typically be similarly visible and accessible through all other Goblaq platforms.</li>
                            </ol>
                        <li>COOKIES</li>
                        We, and third parties with whom we partner, may use cookies, web beacons, tags, scripts, local shared objects such as HTML5 and Flash (sometimes called “flash cookies”), advertising identifiers (including mobile identifiers such as Apple’s IDFA or Google’s Advertising ID) and similar technology (“Cookies”) in connection with your use of the Service, third party websites, and mobile applications. Cookies may have unique identifiers, and reside, among other places, on your computer or mobile device, in emails we send to you, and on our web pages. Cookies may transmit information about you and your use of the Service, such as your browser type, search preferences, IP address, data relating to advertisements that have been displayed to you or that you have clicked on, and the date and time of your use. Cookies may be persistent or stored only during an individual session.
                        <br/>
                        <br/>
                        The purposes for which we use Cookies in the Service include:
                        <Table />
                        You can set some Cookie preferences through your device or browser settings, but doing so may affect the functionality of the Service. The method for disabling Cookies may vary by device and browser, but can usually be found in your device or browser preferences or security settings. For example, iOS and Android devices each have settings which are designed to limit forms of ad tracking. For flash cookies, you can manage your privacy settings by clicking <a href="">here</a>. Please note that changing any of these settings does not prevent the display of certain advertisements to you.
                        <li>THIRD PARTIES</li>
                        Third parties may receive information about you as follows:
                            <ol type="1">
                                <li><strong>Advertisers:</strong> We may allow third parties to use Cookies through the Service to collect the same type of information for the same purposes as we do. In doing so, we adhere to the Digital Advertising Alliance's Self-Regulatory Principles for Online Behavioral Advertising. Third parties may be able to associate the information they collect with other information they have about you from other sources. We do not necessarily have access to or control over the Cookies they use, but you may be able to opt out of some of their practices by visiting the following links: <a href="">Network Advertising Initiative</a>, <a href="">Omniture</a> and <a href="">Digital Advertising Alliance</a>. Please note that opting out does not prevent the display of all advertisements to you. Additionally, we may share non-personally identifiable information from or about you with third parties, such as location data, advertising identifiers, or a cryptographic hash of a common account identifier (such as an email address) to facilitate the display of targeted advertising. You may be able to limit our sharing of some of this information through your mobile device settings, as described in Section 2 above, or through the Service’s settings.</li>
                                <li><strong>Content Partners:</strong> We allow third party partners to use and display some of the public content available through the Service, such as your photos, reviews, and other information detailed in Section 1(b) above.</li>
                                <li><strong>Service Providers:</strong> We may rely on third party providers to support or provide some of the services that are available through the Service, such as reservations and food delivery. We may also rely on third party providers to perform certain services for us in connection with your use of the Service, such as communications and hosting services, network security, technical and customer support, tracking and reporting functions, quality assurance testing, payment processing, our own marketing of the Service, and other functions. We may share information from or about you with these third party providers so that they can perform their services or complete your requests. These third party providers may share information with us that they obtain from or about you in connection with providing their services or completing your requests. Third party providers may also share this information with their subsidiaries, joint ventures, or other companies under common control. Some of our web pages utilize framing techniques to serve content to you from our third party providers, while preserving the look and feel of the Service. In such cases, please note that the information you provide is being provided to the third party.</li>
                                <li><strong>Aggregate or Anonymous Information:</strong> We may share user information in the aggregate with third parties, such as businesses that are listed on Goblaq and content distributors. For example, we may disclose the number of users that have been exposed to, or clicked on, advertisements. We may also disclose anonymized information about your use on Goblaq, for example if you engage in a transaction in connection with Goblaq, we may publicly disclose information about the transaction without providing identifying information about you or otherwise disclosing your participation in the transaction.</li>
                                <li><strong>Business Transfers:</strong> We may share information from or about you with our parent companies, subsidiaries, joint ventures, or other companies under common control, in which case we will require them to honor this Privacy Policy. If another company acquires Goblaq, or all or substantially all of our assets, that company will possess the same information, and will assume the rights and obligations with respect to that information as described in this Privacy Policy.</li>
                                <li><strong>Businesses on Goblaq:</strong> We may share information from or about you (such as your age and gender), your devices, and your use of the Service (such as which businesses you bookmark or call) with businesses listed on Goblaq. You may adjust your <a href="">account settings</a> to increase or decrease the amount of information we share. Keep in mind that businesses may still see your public activity and posts, and may receive information from or about you when you transact or communicate with them, through Goblaq or otherwise, regardless of your settings (see Section 1 above). Additionally, if you make a phone call to a business through or in connection with your use of the Service, we may share information about your call with the business that the business would have received had you called them directly, such as the date and time of your call and your phone number. You may be able to limit our ability to collect and share your phone number through your phone’s settings or phone service provider.</li>
                                <li><strong>Investigations and Legal Disclosures:</strong> We may investigate and disclose information from or about you if we have a good faith belief that such investigation or disclosure: (a) is reasonably necessary to comply with legal process and law enforcement instructions and orders, such as a search warrant, subpoena, statute, judicial proceeding, or other legal process or law enforcement requests served on us; (b) is helpful to prevent, investigate, or identify possible wrongdoing in connection with the Service; or (c) protects our rights, reputation, property, or that of our users, affiliates, or the public, such as disclosures in connection with Goblaq’s Consumer Alerts program. If you flag or otherwise complain to us about content through the Service, we may share the substance of your complaint with the contributor of that content in order to provide an opportunity for the contributor to respond.</li>
                                <li><strong>Links:</strong> The Service may link to third party services, like a business’s URL. Except as set forth herein, we do not share your personal information with them, and are not responsible for their privacy practices. We suggest you read the privacy policies on or applicable to all such third party services.</li>
                                <li><strong>Third Party Accounts:</strong> If you sign up for, or log into, Goblaq using a third party service like Facebook or Google, or link your Goblaq account to your account with a third party service like Facebook or Twitter, we may receive information about you from such third party service. If you post content to a third party service through the Service, that third party service will also receive that content, which will be visible to anyone that has access to it through that third party service.</li>
                            </ol>
                        <li>CONTROLLING YOUR PERSONAL DATA</li>
                        Other users may be able to identify you, or associate you with your account, if you include personal information in the content you post publicly. You can reduce the risk of being personally identified by using the Service pseudonymously, though doing so could detract from the credibility of your contributions to the Service. Goblaq users can also use the Find Friends feature to find one another based on their names or email addresses. You can adjust the settings for this feature in your <a href="">account settings</a>. Please also note that the messages you send or receive using the Service are only private to the extent that both you and the person you are communicating with keep them private. For example, if you send a message to another user, that user may choose to publicly post it. Also, we may access and disclose such messages in the course of investigations relating to use of the Service.
                        <li>DATA RETENTION AND ACCOUNT TERMINATION</li>
                        You can close your account by clicking <a href="">here</a>. We will remove certain public posts from view and/or dissociate them from your account profile, but we may retain information about you for the purposes authorized under this Privacy Policy unless prohibited by law. For example, we may retain information to prevent, investigate, or identify possible wrongdoing in connection with the Service or to comply with legal obligations. Please note that businesses cannot remove their business listings, ratings, or reviews by closing their accounts.
                        <li>CHILDREN</li>
                        The Service is intended for general audiences and is not directed to children under 13. We do not knowingly collect personal information from children under 13. If you become aware that a child has provided us with personal information without parental consent. If we become aware that a child under 13 has provided us with personal information without parental consent, we take steps to remove such information and terminate the child’s account.
                        <li>SECURITY</li>
                        We use various safeguards to protect the personal information submitted to us, both during transmission and once we receive it. However, no method of transmission over the Internet or via mobile device, or method of electronic storage, is 100% secure. Therefore, while we strive to use commercially acceptable means to protect your personal information, we cannot guarantee its absolute security.
                        <li>CONTACT</li>
                        You may contact us online concerning our Privacy Policy, or write to us at the following address:
                        Goblaq, Attn: Data Privacy Manager privacy@goblaq.com
                        <li>MODIFICATIONS TO THIS PRIVACY POLICY</li>
                        We may revise this Privacy Policy from time to time. The most current version of the Privacy Policy will govern our collection, use, and disclosure of information about you and will be located <a href="">here</a>. If we make material changes to this Privacy Policy, we will notify you by email or by posting a notice on the Service prior to the effective date of the changes. By continuing to access or use the Service after those changes become effective, you acknowledge the revised Privacy Policy.
                        <li>TEXAS RESIDENTS: YOUR TEXAS PRIVACY RIGHTS</li>
                        We do not disclose your personal information to third parties for the purpose of directly marketing their goods or services to you unless you first agree to such disclosure. If you have any questions regarding this policy, or would like to change your preferences, you may contact us at the address listed above in Section 8.
                    </ol>

                </Typography>
            </Container>
        </Page>
    )
}

export default PrivacyPolicy; 
